///////////////////////////////////////////////////////////
//  Vinculador.cs
//  Implementation of the Class Vinculador
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:01 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using TPANUAL;

public class Vinculador {

	private List<Condicion> condiciones;
	private CriterioVinculador criterio;

	public Vinculador(){

	}

	public void cambiarCriterio(CriterioVinculador criterio){

	}

	public void cambiarCriterioAMix(List<CriterioVinculador> criterios){

	}

	public bool cumpleCondiciones(){

		return false;
	}

	public void vincular(){

	}
}