/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 10-Sep-2020 12:49:50 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS Ciudad CASCADE
;

DROP TABLE IF EXISTS Compra CASCADE
;

DROP TABLE IF EXISTS Direccion CASCADE
;

DROP TABLE IF EXISTS EntidadBase CASCADE
;

DROP TABLE IF EXISTS EntidadJuridica CASCADE
;

DROP TABLE IF EXISTS EntidadJuridicaProveedora CASCADE
;

DROP TABLE IF EXISTS Item CASCADE
;

DROP TABLE IF EXISTS OperacionDeEgreso CASCADE
;

DROP TABLE IF EXISTS OperacionDeIngreso CASCADE
;

DROP TABLE IF EXISTS Organizacion CASCADE
;

DROP TABLE IF EXISTS Pais CASCADE
;

DROP TABLE IF EXISTS PersonaProveedora CASCADE
;

DROP TABLE IF EXISTS Presupuesto CASCADE
;

DROP TABLE IF EXISTS Provincia CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

DROP TABLE IF EXISTS UsuariosxCompra CASCADE
;

/* Create Tables */

CREATE TABLE Ciudad
(
	ID_Ciudad VARCHAR(50) NOT NULL ,
	nombre VARCHAR(50) NULL,
	ID_Provincia VARCHAR(50) NULL,
	PRIMARY KEY (ID_Ciudad)
)

;

CREATE TABLE UsuariosxCompra
(
	ID_Compra INT NOT NULL,
	ID_Usuario INT NOT NULL,
	CONSTRAINT PK_UsuariosxCompra PRIMARY KEY (ID_Compra ASC, ID_Usuario ASC)
)

;

CREATE TABLE Compra
(
	cantidadDePresupuestosRequeridos INT NULL,
	ID_Compra INT NOT NULL AUTO_INCREMENT,
	ID_Egreso INT NULL,
	PRIMARY KEY (ID_Compra)
)

;

CREATE TABLE Direccion
(
	calle VARCHAR(50) NULL,
	depto VARCHAR(50) NULL,
	piso INT NULL,
	ID_Direccion INT NOT NULL AUTO_INCREMENT,
	ID_Ciudad VARCHAR(50) NULL,
	PRIMARY KEY (ID_Direccion)
)

;

CREATE TABLE EntidadBase
(
	Descripcion VARCHAR(50) NULL,
	ID_EntidadBase INT NOT NULL AUTO_INCREMENT,
	ID_EntidadJuridica INT NULL,
	ID_Organizacion INT NULL,
	PRIMARY KEY (ID_EntidadBase)
)

;

CREATE TABLE EntidadJuridica
(
	CodigoInscripcion VARCHAR(50) NULL,
	CUIT VARCHAR(50) NULL,
	RazonSocial VARCHAR(50) NULL,
	ID_EntidadJuridica INT NOT NULL AUTO_INCREMENT,
	ID_Organizacion INT NULL,
	ID_Direccion INT NULL,
	PRIMARY KEY (ID_EntidadJuridica)
)

;

CREATE TABLE EntidadJuridicaProveedora
(
	codigoInscripcion VARCHAR(50) NULL,
	cuit VARCHAR(50) NULL,
	razonSocial VARCHAR(50) NULL,
	ID_EJProveedora INT NOT NULL AUTO_INCREMENT,
	ID_Compra INT NULL,
	ID_Direccion INT NULL,
	ID_Presupuesto INT NULL,
	PRIMARY KEY (ID_EJProveedora)
)

;

CREATE TABLE Item
(
	valorTotal FLOAT(6,2) NULL,
	nombre VARCHAR(50) NULL,
	descripcion VARCHAR(50) NULL,
	ID_Item INT NOT NULL AUTO_INCREMENT,
	ID_Compra INT NULL,
	ID_Presupuesto INT NULL,
	PRIMARY KEY (ID_Item)
)

;

CREATE TABLE OperacionDeEgreso
(
	Fecha DATE NULL,
	ValorTotal FLOAT(10,2) NULL,
	TipoProv VARCHAR(50) NULL,
	ID_Egreso INT NOT NULL AUTO_INCREMENT,
	ID_Ingreso INT NULL,
	ID_Organizacion INT NULL,
	PRIMARY KEY (ID_Egreso)
)

;

CREATE TABLE OperacionDeIngreso
(
	descripcion VARCHAR(50) NULL,
	monto FLOAT(10,2) NULL,
	ID_Ingreso INT NOT NULL AUTO_INCREMENT,
	ID_Organizacion INT NULL,
	PRIMARY KEY (ID_Ingreso)
)

;

CREATE TABLE Organizacion
(
	NombreFicticio VARCHAR(50) NULL,
	ID_Organizacion INT NOT NULL AUTO_INCREMENT,
	cantidadDePersonal INT NULL,
	actComisionistaoAgenciaDeViaje BOOL NULL,
	promedioVentasAnuales FLOAT(10,2) NULL,
	PRIMARY KEY (ID_Organizacion)
)

;

CREATE TABLE Pais
(
	ID_Pais VARCHAR(50) NOT NULL,
	nombre VARCHAR(50) NULL,
	PRIMARY KEY (ID_Pais)
)

;

CREATE TABLE PersonaProveedora
(
	DNI VARCHAR(50) NULL,
	nombre VARCHAR(50) NULL,
	ID_PersonaProveedora INT NOT NULL AUTO_INCREMENT,
	ID_Compra INT NULL,
	ID_Direccion INT NULL,
	ID_Presupuesto INT NULL,
	PRIMARY KEY (ID_PersonaProveedora)
)

;

CREATE TABLE Presupuesto
(
	detalle VARCHAR(50) NULL,
	ID_Presupuesto INT NOT NULL AUTO_INCREMENT,
	ID_Compra INT NULL,
	PRIMARY KEY (ID_Presupuesto)
)

;

CREATE TABLE Provincia
(
	ID_Provincia VARCHAR(50) NOT NULL ,
	nombre VARCHAR(50) NULL,
	ID_Pais VARCHAR(50) NULL,
	PRIMARY KEY (ID_Provincia)
)

;

CREATE TABLE Usuario
(
	NombreUsuario VARCHAR(50) NULL,
	Contraseña VARCHAR(50) NULL,
	TipoUsuario VARCHAR(50) NULL,
	ID_Usuario INT NOT NULL AUTO_INCREMENT,
	ID_Organizacion INT NULL,
	PRIMARY KEY (ID_Usuario)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE Ciudad 
 ADD CONSTRAINT FK_Provincia_Ciudad
	FOREIGN KEY (ID_Provincia) REFERENCES Provincia (ID_Provincia) ON DELETE SET NULL
;

ALTER TABLE Compra 
 ADD CONSTRAINT FK_OperacionDeEgreso_Compra
	FOREIGN KEY (ID_Egreso) REFERENCES OperacionDeEgreso (ID_Egreso) ON DELETE SET NULL
;

ALTER TABLE Direccion 
 ADD CONSTRAINT FK_Ciudad_Direccion
	FOREIGN KEY (ID_Ciudad) REFERENCES Ciudad (ID_Ciudad) ON DELETE SET NULL
;

ALTER TABLE EntidadBase 
 ADD CONSTRAINT FK_EntidadJuridica_EntidadBase
	FOREIGN KEY (ID_EntidadJuridica) REFERENCES EntidadJuridica (ID_EntidadJuridica) ON DELETE SET NULL
;

ALTER TABLE EntidadBase 
 ADD CONSTRAINT FK_Organizacion_EntidadBase
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE SET NULL
;

ALTER TABLE EntidadJuridica 
 ADD CONSTRAINT FK_Direccion_EntidadJuridica
	FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE SET NULL
;

ALTER TABLE EntidadJuridica 
 ADD CONSTRAINT FK_Organizacion_EntidadJuridica
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE SET NULL
;

ALTER TABLE EntidadJuridicaProveedora 
 ADD CONSTRAINT FK_Compra_EntidadJuridicaProveedora
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE SET NULL
;

ALTER TABLE EntidadJuridicaProveedora 
 ADD CONSTRAINT FK_Direccion_EntidadJuridicaProveedora
	FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE SET NULL
;

ALTER TABLE EntidadJuridicaProveedora 
 ADD CONSTRAINT FK_Presupuesto_EntidadJuridicaProveedora
	FOREIGN KEY (ID_Presupuesto) REFERENCES Presupuesto (ID_Presupuesto) ON DELETE SET NULL
;

ALTER TABLE Item 
 ADD CONSTRAINT FK_Compra_Item
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE SET NULL
;

ALTER TABLE Item 
 ADD CONSTRAINT FK_Presupuesto_Item
	FOREIGN KEY (ID_Presupuesto) REFERENCES Presupuesto (ID_Presupuesto) ON DELETE SET NULL
;

ALTER TABLE OperacionDeEgreso 
 ADD CONSTRAINT FK_OperacionDeIngreso_OperacionDeEgreso
	FOREIGN KEY (ID_Ingreso) REFERENCES OperacionDeIngreso (ID_Ingreso) ON DELETE SET NULL
;

ALTER TABLE OperacionDeEgreso 
 ADD CONSTRAINT FK_Organizacion_OperacionDeEgreso
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE SET NULL
;

ALTER TABLE OperacionDeIngreso 
 ADD CONSTRAINT FK_Organizacion_OperacionDeIngreso
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE SET NULL
;

ALTER TABLE PersonaProveedora 
 ADD CONSTRAINT FK_Compra_PersonaProveedora
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE SET NULL
;

ALTER TABLE PersonaProveedora 
 ADD CONSTRAINT FK_Direccion_PersonaProveedora
	FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE SET NULL
;

ALTER TABLE PersonaProveedora 
 ADD CONSTRAINT FK_Presupuesto_PersonaProveedora
	FOREIGN KEY (ID_Presupuesto) REFERENCES Presupuesto (ID_Presupuesto) ON DELETE SET NULL
;

ALTER TABLE Presupuesto 
 ADD CONSTRAINT FK_Compra_Presupuesto
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE SET NULL
;

ALTER TABLE Provincia 
 ADD CONSTRAINT FK_Pais_Provincia
	FOREIGN KEY (ID_Pais) REFERENCES Pais (ID_Pais) ON DELETE SET NULL
;

ALTER TABLE Usuario 
 ADD CONSTRAINT FK_Organizacion_Usuario
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE SET NULL
;

ALTER TABLE UsuariosxCompra
 ADD CONSTRAINT FK_UsuariosxCompra_Compra
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE usuariosxCompra 
 ADD CONSTRAINT FK_UsuariosxCompra_Usuario
	FOREIGN KEY (ID_Usuario) REFERENCES usuario (ID_Usuario) ON DELETE Restrict ON UPDATE Restrict
;