/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 14-sep.-2020 23:06:10 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS Ciudad CASCADE
;

DROP TABLE IF EXISTS Compra CASCADE
;

DROP TABLE IF EXISTS Direccion CASCADE
;

DROP TABLE IF EXISTS DocumentoComercial CASCADE
;

DROP TABLE IF EXISTS EntidadBase CASCADE
;

DROP TABLE IF EXISTS EntidadJuridica CASCADE
;

DROP TABLE IF EXISTS EntidadJuridicaProveedora CASCADE
;

DROP TABLE IF EXISTS Item CASCADE
;

DROP TABLE IF EXISTS MedioDePago CASCADE
;

DROP TABLE IF EXISTS Moneda CASCADE
;

DROP TABLE IF EXISTS OperacionDeEgreso CASCADE
;

DROP TABLE IF EXISTS OperacionDeIngreso CASCADE
;

DROP TABLE IF EXISTS Organizacion CASCADE
;

DROP TABLE IF EXISTS Pais CASCADE
;

DROP TABLE IF EXISTS PersonaProveedora CASCADE
;

DROP TABLE IF EXISTS Presupuesto CASCADE
;

DROP TABLE IF EXISTS Provincia CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

DROP TABLE IF EXISTS UsuariosxCompra CASCADE
;

/* Create Tables */

CREATE TABLE Ciudad
(
	ID_Ciudad VARCHAR(50) NOT NULL,
	Nombre VARCHAR(50) NULL,
	ID_Provincia VARCHAR(50) NULL,
	CONSTRAINT PK_Ciudad PRIMARY KEY (ID_Ciudad ASC)
)

;

CREATE TABLE Compra
(
	CantidadDePresupuestosRequeridos INT NULL,
	ID_Compra INT NOT NULL AUTO_INCREMENT,
	ID_Egreso INT NULL,
	CONSTRAINT PK_Compra PRIMARY KEY (ID_Compra ASC)
)

;

CREATE TABLE Direccion
(
	Calle VARCHAR(50) NULL,
	Depto VARCHAR(50) NULL,
	Piso INT NULL,
	ID_Direccion INT NOT NULL AUTO_INCREMENT,
	ID_Ciudad VARCHAR(50) NULL,
	CONSTRAINT PK_Direccion PRIMARY KEY (ID_Direccion ASC)
)

;

CREATE TABLE DocumentoComercial
(
	ID_Documento INT NOT NULL AUTO_INCREMENT,
	TipoDocumento VARCHAR(50) NULL,
	ID_Egreso INT NULL,
	ID_Presupuesto INT NULL,
	CONSTRAINT PK_DocumentoComercial PRIMARY KEY (ID_Documento ASC)
)

;

CREATE TABLE EntidadBase
(
	Descripcion VARCHAR(50) NULL,
	ID_EntidadBase INT NOT NULL AUTO_INCREMENT,
	ID_EntidadJuridica INT NULL,
	ID_Organizacion INT NULL,
	CONSTRAINT PK_EntidadBase PRIMARY KEY (ID_EntidadBase ASC)
)

;

CREATE TABLE EntidadJuridica
(
	CodigoInscripcion VARCHAR(50) NULL,
	CUIT VARCHAR(50) NULL,
	RazonSocial VARCHAR(50) NULL,
	ID_EntidadJuridica INT NOT NULL AUTO_INCREMENT,
	ID_Organizacion INT NULL,
	ID_Direccion INT NULL,
	CONSTRAINT PK_EntidadJuridica PRIMARY KEY (ID_EntidadJuridica ASC)
)

;

CREATE TABLE EntidadJuridicaProveedora
(
	CodigoInscripcion VARCHAR(50) NULL,
	CUIT VARCHAR(50) NULL,
	RazonSocial VARCHAR(50) NULL,
	ID_EJProveedora INT NOT NULL AUTO_INCREMENT,
	ID_Compra INT NULL,
	ID_Direccion INT NULL,
	ID_Presupuesto INT NULL,
	CONSTRAINT PK_EntidadJuridicaProveedora PRIMARY KEY (ID_EJProveedora ASC)
)

;

CREATE TABLE Item
(
	ValorTotal FLOAT NULL,
	Nombre VARCHAR(50) NULL,
	Descripcion VARCHAR(50) NULL,
	ID_Item INT NOT NULL AUTO_INCREMENT,
	ID_Compra INT NULL,
	ID_Presupuesto INT NULL,
	CONSTRAINT PK_Item PRIMARY KEY (ID_Item ASC)
)

;

CREATE TABLE MedioDePago
(
	Numero VARCHAR(50) NULL,
	TipoPago VARCHAR(50) NULL,
	ID_MedioDePago INT NOT NULL AUTO_INCREMENT,
	ID_Pais VARCHAR(50) NULL,
	CONSTRAINT PK_MedioDePago PRIMARY KEY (ID_MedioDePago ASC)
)

;

CREATE TABLE Moneda
(
	ID_Moneda VARCHAR(50) NOT NULL,
	Simbolo VARCHAR(50) NULL,
	Descripcion VARCHAR(50) NULL,
	CONSTRAINT PK_Moneda PRIMARY KEY (ID_Moneda ASC)
)

;

CREATE TABLE OperacionDeEgreso
(
	Fecha DATE NULL,
	ValorTotal FLOAT NULL,
	ID_Egreso INT NOT NULL AUTO_INCREMENT,
	ID_Ingreso INT NULL,
	ID_Organizacion INT NULL,
	ID_MedioDePago INT NULL,
	CONSTRAINT PK_OperacionDeEgreso PRIMARY KEY (ID_Egreso ASC)
)

;

CREATE TABLE OperacionDeIngreso
(
	Descripcion VARCHAR(50) NULL,
	Monto FLOAT NULL,
	ID_Ingreso INT NOT NULL AUTO_INCREMENT,
	ID_Organizacion INT NULL,
	CONSTRAINT PK_OperacionDeIngreso PRIMARY KEY (ID_Ingreso ASC)
)

;

CREATE TABLE Organizacion
(
	NombreFicticio VARCHAR(50) NULL,
	ID_Organizacion INT NOT NULL AUTO_INCREMENT,
	CantidadDePersonal INT NULL,
	ActComisionistaoAgenciaDeViaje BOOL NULL,
	PromedioVentasAnuales FLOAT NULL,
	CONSTRAINT PK_Organizacion PRIMARY KEY (ID_Organizacion ASC)
)

;

CREATE TABLE Pais
(
	ID_Pais VARCHAR(50) NOT NULL,
	Nombre VARCHAR(50) NULL,
	ID_Moneda VARCHAR(50) NULL,
	CONSTRAINT PK_Pais PRIMARY KEY (ID_Pais ASC)
)

;

CREATE TABLE PersonaProveedora
(
	DNI VARCHAR(50) NULL,
	Nombre VARCHAR(50) NULL,
	ID_PersonaProveedora INT NOT NULL AUTO_INCREMENT,
	ID_Compra INT NULL,
	ID_Direccion INT NULL,
	ID_Presupuesto INT NULL,
	CONSTRAINT PK_PersonaProveedora PRIMARY KEY (ID_PersonaProveedora ASC)
)

;

CREATE TABLE Presupuesto
(
	Detalle VARCHAR(50) NULL,
	ID_Presupuesto INT NOT NULL AUTO_INCREMENT,
	ID_Compra INT NULL,
    ValorTotal FLOAT NULL,
	CONSTRAINT PK_Presupuesto PRIMARY KEY (ID_Presupuesto ASC)
)

;

CREATE TABLE Provincia
(
	ID_Provincia VARCHAR(50) NOT NULL,
	Nombre VARCHAR(50) NULL,
	ID_Pais VARCHAR(50) NULL,
	CONSTRAINT PK_Provincia PRIMARY KEY (ID_Provincia ASC)
)

;

CREATE TABLE Usuario
(
	NombreUsuario VARCHAR(50) NULL,
	Contraseña VARCHAR(50) NULL,
	TipoUsuario VARCHAR(50) NULL,
	ID_Usuario INT NOT NULL AUTO_INCREMENT,
	ID_Organizacion INT NULL,
	CONSTRAINT PK_Usuario PRIMARY KEY (ID_Usuario ASC)
)

;

CREATE TABLE UsuariosxCompra
(
	ID_Compra INT NOT NULL,
	ID_Usuario INT NOT NULL,
	CONSTRAINT PK_UsuariosxCompra PRIMARY KEY (ID_Compra ASC, ID_Usuario ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE Ciudad 
 ADD CONSTRAINT FK_Provincia_Ciudad
	FOREIGN KEY (ID_Provincia) REFERENCES Provincia (ID_Provincia) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Compra 
 ADD CONSTRAINT FK_OperacionDeEgreso_Compra
	FOREIGN KEY (ID_Egreso) REFERENCES OperacionDeEgreso (ID_Egreso) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Direccion 
 ADD CONSTRAINT FK_Ciudad_Direccion
	FOREIGN KEY (ID_Ciudad) REFERENCES Ciudad (ID_Ciudad) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE DocumentoComercial 
 ADD CONSTRAINT FK_OperacionDeEgreso_DocumentoComercial
	FOREIGN KEY (ID_Egreso) REFERENCES OperacionDeEgreso (ID_Egreso) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE DocumentoComercial 
 ADD CONSTRAINT FK_Presupuesto_DocumentoComercial
	FOREIGN KEY (ID_Presupuesto) REFERENCES Presupuesto (ID_Presupuesto) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE EntidadBase 
 ADD CONSTRAINT FK_EntidadJuridica_EntidadBase
	FOREIGN KEY (ID_EntidadJuridica) REFERENCES EntidadJuridica (ID_EntidadJuridica) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE EntidadBase 
 ADD CONSTRAINT FK_Organizacion_EntidadBase
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE EntidadJuridica 
 ADD CONSTRAINT FK_Direccion_EntidadJuridica
	FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE EntidadJuridica 
 ADD CONSTRAINT FK_Organizacion_EntidadJuridica
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE EntidadJuridicaProveedora 
 ADD CONSTRAINT FK_Compra_EntidadJuridicaProveedora
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE EntidadJuridicaProveedora 
 ADD CONSTRAINT FK_Direccion_EntidadJuridicaProveedora
	FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE EntidadJuridicaProveedora 
 ADD CONSTRAINT FK_Presupuesto_EntidadJuridicaProveedora
	FOREIGN KEY (ID_Presupuesto) REFERENCES Presupuesto (ID_Presupuesto) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Item 
 ADD CONSTRAINT FK_Compra_Item
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Item 
 ADD CONSTRAINT FK_Presupuesto_Item
	FOREIGN KEY (ID_Presupuesto) REFERENCES Presupuesto (ID_Presupuesto) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE MedioDePago 
 ADD CONSTRAINT FK_Pais_MedioDePago
	FOREIGN KEY (ID_Pais) REFERENCES Pais (ID_Pais) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE OperacionDeEgreso 
 ADD CONSTRAINT FK_MedioDePago_OperacionDeEgreso
	FOREIGN KEY (ID_MedioDePago) REFERENCES MedioDePago (ID_MedioDePago) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE OperacionDeEgreso 
 ADD CONSTRAINT FK_OperacionDeIngreso_OperacionDeEgreso
	FOREIGN KEY (ID_Ingreso) REFERENCES OperacionDeIngreso (ID_Ingreso) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE OperacionDeEgreso 
 ADD CONSTRAINT FK_Organizacion_OperacionDeEgreso
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE OperacionDeIngreso 
 ADD CONSTRAINT FK_Organizacion_OperacionDeIngreso
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Pais 
 ADD CONSTRAINT FK_Moneda_Pais
	FOREIGN KEY (ID_Moneda) REFERENCES Moneda (ID_Moneda) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE PersonaProveedora 
 ADD CONSTRAINT FK_Compra_PersonaProveedora
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE PersonaProveedora 
 ADD CONSTRAINT FK_Direccion_PersonaProveedora
	FOREIGN KEY (ID_Direccion) REFERENCES Direccion (ID_Direccion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE PersonaProveedora 
 ADD CONSTRAINT FK_Presupuesto_PersonaProveedora
	FOREIGN KEY (ID_Presupuesto) REFERENCES Presupuesto (ID_Presupuesto) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Presupuesto 
 ADD CONSTRAINT FK_Compra_Presupuesto
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Provincia 
 ADD CONSTRAINT FK_Pais_Provincia
	FOREIGN KEY (ID_Pais) REFERENCES Pais (ID_Pais) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Usuario 
 ADD CONSTRAINT FK_Organizacion_Usuario
	FOREIGN KEY (ID_Organizacion) REFERENCES Organizacion (ID_Organizacion) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE UsuariosxCompra 
 ADD CONSTRAINT FK_UsuariosxCompra_Compra
	FOREIGN KEY (ID_Compra) REFERENCES Compra (ID_Compra) ON DELETE restrict ON UPDATE restrict
;

ALTER TABLE UsuariosxCompra 
 ADD CONSTRAINT FK_UsuariosxCompra_Usuario
	FOREIGN KEY (ID_Usuario) REFERENCES Usuario (ID_Usuario) ON DELETE Restrict ON UPDATE Restrict
;
 
