///////////////////////////////////////////////////////////
//  Mix.cs
//  Implementation of the Class Mix
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:05 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// This class implements the algorithm using the Strategy interface.
/// </summary>
public class Mix : Criterio {

	private Criterio criterios;
	public Criterio m_Criterio;

	public Mix(){

	}

	~Mix(){

	}

	public override void vincular(){

	}

}//end Mix