///////////////////////////////////////////////////////////
//  Orden-Valor-PrimeroIngreso.cs
//  Implementation of the Class Orden-Valor-PrimeroIngreso
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:04 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// This class implements the algorithm using the Strategy interface.
/// </summary>
public class Orden-Valor-PrimeroIngreso : Criterio {

	public Orden-Valor-PrimeroIngreso(){

	}

	~Orden-Valor-PrimeroIngreso(){

	}

	public override void vincular(){

	}

}//end Orden-Valor-PrimeroIngreso