///////////////////////////////////////////////////////////
//  Orden-Valor-PrimeroEgreso.cs
//  Implementation of the Class Orden-Valor-PrimeroEgreso
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:03 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// This class implements the algorithm using the Strategy interface.
/// </summary>
public class Orden_Valor_PrimeroEgreso : Criterio {

	public Orden-Valor-PrimeroEgreso(){

	}

	~Orden-Valor-PrimeroEgreso(){

	}

	public override void vincular(){

	}

}//end Orden-Valor-PrimeroEgreso