///////////////////////////////////////////////////////////
//  Vinculador.cs
//  Implementation of the Class Vinculador
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:01 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// This class is configured with a ConcreteStrategy object, maintains a reference
/// to a Strategy object and may define an interface that lets Strategy access its
/// data.
/// </summary>
public class Vinculador {

	private Condicion condiciones;
	private Criterio criterio;
	private Organizacion organizacion;
	private Criterio strategy;

	public Vinculador(){

	}

	~Vinculador(){

	}

	/// 
	/// <param name="strategy"></param>
	public void cambiarCriterio(Criterio strategy){

		//this.strategy = strategy;


	}

	/// 
	/// <param name="Criterios"></param>
	public void cambiarCriterioAMix(Criterios Criterios){

	}

	public bool cumpleCondiciones(){

		return false;
	}

	public void vincular(){

		//strategy.AlgorithmInterface();


	}

}//end Vinculador