///////////////////////////////////////////////////////////
//  Condicion.cs
//  Implementation of the Class Condicion
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:06 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

/// <summary>
/// This class declares an interface common to all supported algorithms. Context
/// uses this interface to call the algorithm defined by a ConcreteStrategy.
/// </summary>
public abstract class Condicion {

	public Condicion(){

	}

	public abstract bool cumpleCondicion();

}//end Condicion