///////////////////////////////////////////////////////////
//  Actividad.cs
//  Implementation of the Class Actividad
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class Actividad {

		private int cantidadPersonalMax;
		private int cantidadVentasMax;

		public Actividad(){

		}

		~Actividad(){

		}

	}//end Actividad

	public enum Actividad : int {

		agropecuario,
		industriaMineria,
		servicios,
		construccion,
		comercio

	}//end Actividad

}//end namespace TP-ANUAL