///////////////////////////////////////////////////////////
//  Agropecuario.cs
//  Implementation of the Class Agropecuario
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Agropecuario : Actividad {

		public Agropecuario(){

		}

		~Agropecuario(){

		}

	}//end Agropecuario

}//end namespace TP-ANUAL