///////////////////////////////////////////////////////////
//  Boleta de Deposito.cs
//  Implementation of the Class Boleta de Deposito
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Boleta de Deposito : TipoDocumento {

		public Boleta de Deposito(){

		}

		~Boleta de Deposito(){

		}

	}//end Boleta de Deposito

}//end namespace TP-ANUAL