///////////////////////////////////////////////////////////
//  Compra.cs
//  Implementation of the Class Compra
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Compra : Tipo Egreso {

		private string bandejaDeMensajes;
		private Criterio criterio;
		private Presupuesto presupuestoElegido;
		private Presupuesto presupuestos;
		private Producto productosRequeridos;
		private Usuario revisores;
		public TP-ANUAL.Presupuesto m_Presupuesto;
		public TP-ANUAL.Producto m_Producto;
		public TP-ANUAL.Usuario m_Usuario;
		public TP-ANUAL.Criterio m_Criterio;

		public Compra(){

		}

		~Compra(){

		}

		/// 
		/// <param name="usuario"></param>
		public void agregarRevisor(Usuario usuario){

		}

		public boolean validarCompra(){

			return null;
		}

		public float valorTotal(){

			return 0;
		}

	}//end Compra

}//end namespace TP-ANUAL