///////////////////////////////////////////////////////////
//  Construccion.cs
//  Implementation of the Class Construccion
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Construccion : Actividad {

		public Construccion(){

		}

		~Construccion(){

		}

	}//end Construccion

}//end namespace TP-ANUAL