///////////////////////////////////////////////////////////
//  Criterio.cs
//  Implementation of the Class Criterio
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class Criterio {

		public Criterio(){

		}

		~Criterio(){

		}

		public void seleccionarCriterio(){

		}

	}//end Criterio

}//end namespace TP-ANUAL