///////////////////////////////////////////////////////////
//  Documento Comercial.cs
//  Implementation of the Class Documento Comercial
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Documento Comercial {

		private string IDdocumento;
		private TipoDocumento tipoDocumento;
		public TP-ANUAL.TipoDocumento m_TipoDocumento;
		public TP-ANUAL.Presupuesto m_Presupuesto;

		public Documento Comercial(){

		}

		~Documento Comercial(){

		}

	}//end Documento Comercial

}//end namespace TP-ANUAL