///////////////////////////////////////////////////////////
//  Empresa.cs
//  Implementation of the Class Empresa
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Empresa : TipoOrganizacion {

		public Empresa(){

		}

		~Empresa(){

		}

	}//end Empresa

}//end namespace TP-ANUAL