///////////////////////////////////////////////////////////
//  Entidad base.cs
//  Implementation of the Class Entidad base
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Entidad base : TipoEntidad {

		private string descripcion;
		private Entidad Juridica juridicaAsociada;

		public Entidad base(){

		}

		~Entidad base(){

		}

	}//end Entidad base

}//end namespace TP-ANUAL