///////////////////////////////////////////////////////////
//  Entidad Juridica Proveedora.cs
//  Implementation of the Class Entidad Juridica Proveedora
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Entidad Juridica Proveedora : Proveedor {

		private string codigoInscripcion;
		private string CUIT;
		private string razonSocial;

		public Entidad Juridica Proveedora(){

		}

		~Entidad Juridica Proveedora(){

		}

	}//end Entidad Juridica Proveedora

}//end namespace TP-ANUAL