///////////////////////////////////////////////////////////
//  Entidad Juridica.cs
//  Implementation of the Class Entidad Juridica
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Entidad Juridica : TipoEntidad {

		private Entidad base basesAsociadas;
		private string codigoInscripcion;
		private string CUIT;
		private string direccionPostal;
		private string razonSocial;
		public Entidad base m_Entidad base;

		public Entidad Juridica(){

		}

		~Entidad Juridica(){

		}

	}//end Entidad Juridica

}//end namespace TP-ANUAL