///////////////////////////////////////////////////////////
//  Estructura.cs
//  Implementation of the Class Estructura
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:52
//  Original author: Dell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class Estructura {

		public Estructura(){

		}

		~Estructura(){

		}

	}//end Estructura

}//end namespace TP-ANUAL