///////////////////////////////////////////////////////////
//  Factura.cs
//  Implementation of the Class Factura
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Factura : TipoDocumento {

		public Factura(){

		}

		~Factura(){

		}

	}//end Factura

}//end namespace TP-ANUAL