///////////////////////////////////////////////////////////
//  Industria Y Mineria.cs
//  Implementation of the Class Industria Y Mineria
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Industria Y Mineria : Actividad {

		public Industria Y Mineria(){

		}

		~Industria Y Mineria(){

		}

	}//end Industria Y Mineria

}//end namespace TP-ANUAL