///////////////////////////////////////////////////////////
//  MedianaTramo1.cs
//  Implementation of the Class MedianaTramo1
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class MedianaTramo1 : Estructura {

		public MedianaTramo1(){

		}

		~MedianaTramo1(){

		}

	}//end MedianaTramo1

}//end namespace TP-ANUAL