///////////////////////////////////////////////////////////
//  MedianaTramo2.cs
//  Implementation of the Class MedianaTramo2
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Dell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class MedianaTramo2 : Estructura {

		public MedianaTramo2(){

		}

		~MedianaTramo2(){

		}

	}//end MedianaTramo2

}//end namespace TP-ANUAL