///////////////////////////////////////////////////////////
//  Medio de Pago.cs
//  Implementation of the Class Medio de Pago
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class Medio de Pago {

		private string IDpais;
		private string numero;
		private string tipoPago;

		public Medio de Pago(){

		}

		~Medio de Pago(){

		}

	}//end Medio de Pago

}//end namespace TP-ANUAL