///////////////////////////////////////////////////////////
//  MenorValor.cs
//  Implementation of the Class MenorValor
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class MenorValor : Criterio {

		public MenorValor(){

		}

		~MenorValor(){

		}

		public void seleccionarCriterio(){

		}

	}//end MenorValor

}//end namespace TP-ANUAL