///////////////////////////////////////////////////////////
//  Nota de Credito.cs
//  Implementation of the Class Nota de Credito
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Nota de Credito : TipoDocumento {

		public Nota de Credito(){

		}

		~Nota de Credito(){

		}

	}//end Nota de Credito

}//end namespace TP-ANUAL