///////////////////////////////////////////////////////////
//  Nota de Debito.cs
//  Implementation of the Class Nota de Debito
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Nota de Debito : TipoDocumento {

		public Nota de Debito(){

		}

		~Nota de Debito(){

		}

	}//end Nota de Debito

}//end namespace TP-ANUAL