///////////////////////////////////////////////////////////
//  Operacion de egreso.cs
//  Implementation of the Class Operacion de egreso
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class Operacion de egreso {

		private Documento Comercial documentosComerciales;
		private date fechaOperacion;
		private Medio de Pago medioDePago;
		private Tipo Egreso tipoEgreso;
		public Medio de Pago m_Medio de Pago;
		public Documento Comercial m_Documento Comercial;
		public Tipo Egreso m_Tipo Egreso;

		public Operacion de egreso(){

		}

		~Operacion de egreso(){

		}

		public float valorTotal(){

			return 0;
		}

	}//end Operacion de egreso

}//end namespace TP-ANUAL