///////////////////////////////////////////////////////////
//  Orden de Compra.cs
//  Implementation of the Class Orden de Compra
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Orden de Compra : TipoDocumento {

		public Orden de Compra(){

		}

		~Orden de Compra(){

		}

	}//end Orden de Compra

}//end namespace TP-ANUAL