///////////////////////////////////////////////////////////
//  OSC.cs
//  Implementation of the Class OSC
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class OSC : TipoOrganizacion {

		public OSC(){

		}

		~OSC(){

		}

	}//end OSC

}//end namespace TP-ANUAL