///////////////////////////////////////////////////////////
//  Pagare.cs
//  Implementation of the Class Pagare
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:53
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Pagare : TipoDocumento {

		public Pagare(){

		}

		~Pagare(){

		}

	}//end Pagare

}//end namespace TP-ANUAL