///////////////////////////////////////////////////////////
//  Pequeña.cs
//  Implementation of the Class Pequeña
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Pequeña : Estructura {

		public Pequeña(){

		}

		~Pequeña(){

		}

	}//end Pequeña

}//end namespace TP-ANUAL