///////////////////////////////////////////////////////////
//  Persona.cs
//  Implementation of the Class Persona
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Persona : Proveedor {

		private string DNI;
		private string nombre;

		public Persona(){

		}

		~Persona(){

		}

	}//end Persona

}//end namespace TP-ANUAL