///////////////////////////////////////////////////////////
//  Presupuesto.cs
//  Implementation of the Class Presupuesto
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Presupuesto {

		private string detalle;
		private Documento Comercial documentosComerciales;
		private Producto productos;
		private Proveedor proveedor;
		public TP-ANUAL.Proveedor m_Proveedor;
		public TP-ANUAL.Producto m_Producto;
		public Documento Comercial m_Documento Comercial;

		public Presupuesto(){

		}

		~Presupuesto(){

		}

		public float valorTotal(){

			return 0;
		}

	}//end Presupuesto

}//end namespace TP-ANUAL