///////////////////////////////////////////////////////////
//  Producto.cs
//  Implementation of the Class Producto
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Producto {

		private int cantidad;
		private string descripcion;
		private string idProducto;
		private float valor;
		public TP-ANUAL.Compra m_Compra;
		public TP-ANUAL.Presupuesto m_Presupuesto;
		public TP-ANUAL.Proveedor m_Proveedor;

		public Producto(){

		}

		~Producto(){

		}

		public float valorTotal(){

			return 0;
		}

	}//end Producto

}//end namespace TP-ANUAL