///////////////////////////////////////////////////////////
//  Proveedor.cs
//  Implementation of the Class Proveedor
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Proveedor {

		private string direccionPostal;
		private Producto productosDisponibles;
		public TP-ANUAL.Producto m_Producto;

		public Proveedor(){

		}

		~Proveedor(){

		}

		/// 
		/// <param name="producto"></param>
		public void asignarValoresProducto(Producto producto){

		}

	}//end Proveedor

}//end namespace TP-ANUAL