///////////////////////////////////////////////////////////
//  Remito.cs
//  Implementation of the Class Remito
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Remito : TipoDocumento {

		public Remito(){

		}

		~Remito(){

		}

	}//end Remito

}//end namespace TP-ANUAL