///////////////////////////////////////////////////////////
//  Servicios.cs
//  Implementation of the Class Servicios
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class Servicios : Actividad {

		public Servicios(){

		}

		~Servicios(){

		}

	}//end Servicios

}//end namespace TP-ANUAL