///////////////////////////////////////////////////////////
//  Tipo Egreso.cs
//  Implementation of the Class Tipo Egreso
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class Tipo Egreso {

		public Tipo Egreso(){

		}

		~Tipo Egreso(){

		}

	}//end Tipo Egreso

}//end namespace TP-ANUAL