///////////////////////////////////////////////////////////
//  TipoOrganizacion.cs
//  Implementation of the Class TipoOrganizacion
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using TP-ANUAL;
namespace TP-ANUAL {
	public class TipoOrganizacion {

		private Estructura estructura;
		private Organizacion organizacionAsociada;
		public TP-ANUAL.Estructura m_Estructura;

		public TipoOrganizacion(){

		}

		~TipoOrganizacion(){

		}

		public void definirEstructura(){

		}

		/// 
		/// <param name="i"></param>
		public void definirTamaño(int i){

		}

	}//end TipoOrganizacion

}//end namespace TP-ANUAL