///////////////////////////////////////////////////////////
//  TipoDocumento.cs
//  Implementation of the Class TipoDocumento
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class TipoDocumento {

		public TipoDocumento(){

		}

		~TipoDocumento(){

		}

	}//end TipoDocumento

}//end namespace TP-ANUAL