///////////////////////////////////////////////////////////
//  TipoEntidad.cs
//  Implementation of the Class TipoEntidad
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Dell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class TipoEntidad {

		public TipoEntidad(){

		}

		~TipoEntidad(){

		}

	}//end TipoEntidad

}//end namespace TP-ANUAL