///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      29-may.-2020 19:05:54
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace TP-ANUAL {
	public class Usuario {

		private string constraseña;
		private string nombreUsuario;
		private string tipoUsuario;

		public Usuario(){

		}

		~Usuario(){

		}

	}//end Usuario

}//end namespace TP-ANUAL