///////////////////////////////////////////////////////////
//  Criterio.cs
//  Implementation of the Class Criterio
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:02 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using TPANUAL;

public abstract class CriterioVinculador {

	public CriterioVinculador(){

	}
	public abstract void vincular(DB_Context _contexto, Organizacion _org);

	public void asociarEgresoIngreso(OperacionDeEgreso _egreso, OperacionDeIngreso _ingreso)
	{
		/* 
		contexto.Database
			.ExecuteSqlCommand(
			"UPDATE OperacionDeEgreso SET ID_Ingreso = {0} WHERE ID_OperacionDeEgreso = {1}", _ingreso.ID_Ingreso, _egreso.ID_OperacionDeEgreso);

		   UPDATE OperacionDeEgreso  
		   SET ID_Ingreso = ingreso.ID_Ingreso
		   WHERE ID_OperacionDeEgreso = egreso.ID_Egreso
		 */
	}
}