///////////////////////////////////////////////////////////
//  Criterio.cs
//  Implementation of the Class Criterio
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:02 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using TPANUAL;

public abstract class CriterioVinculador {

	public CriterioVinculador(){

	}
	public abstract void vincular(DB_Context contexto, Organizacion organizacion);

	public void asociarEgresoIngreso(DB_Context contexto, OperacionDeEgreso egreso, OperacionDeIngreso ingreso)
	{
		contexto.Database
			.ExecuteSqlCommand(
			"UPDATE OperacionDeEgreso SET IngresoAsociado_ID_Ingreso = {0} WHERE (ID_OperacionDeEgreso = {1}) and (IngresoAsociado_ID_Ingreso is null)", ingreso.ID_Ingreso, egreso.ID_OperacionDeEgreso);
	}
}