///////////////////////////////////////////////////////////
//  Fecha.cs
//  Implementation of the Class Fecha
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:04 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using TPANUAL;

public class Fecha : CriterioVinculador {

	public Fecha(){

	}

	public override void vincular(){

	}

}