///////////////////////////////////////////////////////////
//  Orden-Valor-PrimeroEgreso.cs
//  Implementation of the Class Orden-Valor-PrimeroEgreso
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:03 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System;
using System.Linq;
using TPANUAL;

public class Orden_Valor_PrimeroEgreso : CriterioVinculador {

	public Orden_Valor_PrimeroEgreso(){

	}

	public override void vincular(DB_Context _contexto, Organizacion _org){

		var listaIngresos = _contexto.operacionDeIngreso
			.SqlQuery("Select * from operaciondeingreso where ID_Organizacion = {0}", _org.ID_Organizacion)
			.ToList();

		var listaEgresos = _contexto.operacionDeEgreso
			.SqlQuery("Select * from operaciondeegreso where ID_Organizacion = {0}", _org.ID_Organizacion)
			.ToList();

		Console.WriteLine(listaIngresos.Count);
		Console.WriteLine(listaEgresos.Count);
		Console.ReadLine();
		
		/*
		// Guarda la diferencia restante entre ingreso y egreso
		float montoIngresoRestante;
		foreach (OperacionDeIngreso ingreso in listaIngresos)
		{
			// Le asigna el valor del ingreso al principio del foreach
			montoIngresoRestante = ingreso.Monto;

			// Para cada egreso 
			foreach (OperacionDeEgreso egreso in listaEgresos)
			{
				// Chequeo si puedo asociar el egreso al ingreso
				if ((ingreso.Monto >= egreso.valorTotal()) ||
				   // O si lo que me falta para asociarlo es mayor al valor del egreso 
				   (montoIngresoRestante >= egreso.valorTotal()))
				{
					// Si se puede, lo asocio
					base.asociarEgresoIngreso(egreso, ingreso);

					// Guardo lo que me falta para llenar el ingreso
					montoIngresoRestante -= egreso.valorTotal();

					// Saco el egreso que acabo de vicular, para no vincularlo de nuevo a nada
					listaEgresos.Remove(egreso);
				}
			}
		}
		*/

	}
}