///////////////////////////////////////////////////////////
//  Orden-Valor-PrimeroIngreso.cs
//  Implementation of the Class Orden-Valor-PrimeroIngreso
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:04 PM
//  Original author: Franco
///////////////////////////////////////////////////////////
using System.Collections.Generic;
using TPANUAL;

public class Orden_Valor_PrimeroIngreso : CriterioVinculador {

	public Orden_Valor_PrimeroIngreso(){

	}
	public override void vincular(){

	}

}