///////////////////////////////////////////////////////////
//  PeriodoDeAceptabilidad.cs
//  Implementation of the Class PeriodoDeAceptabilidad
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:07 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

public class PeriodoDeAceptabilidad : Condicion {

	private int periodoDeAceptabilidad;

	public PeriodoDeAceptabilidad(){

	}

	public override bool cumpleCondicion(){

		return false;
	}

}