///////////////////////////////////////////////////////////
//  PeriodoDeAceptabilidad.cs
//  Implementation of the Class PeriodoDeAceptabilidad
//  Generated by Enterprise Architect
//  Created on:      12-Sep-2020 7:23:07 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using TPANUAL;

public class PeriodoDeAceptabilidad : Condicion {

	private int periodo;

	public PeriodoDeAceptabilidad(int dias){
		periodo = dias;
	}

    public int Periodo { get => periodo; set => periodo = value; }

    public override bool cumpleCondicion(OperacionDeEgreso opegreso, OperacionDeIngreso opingreso){
		return true;
	}

}